### ISSUE TITLE
"wrong number of arguments (given 5, expected 3..4)" while insert into Bigquery

### ISSUE THREAD

**Issue by syshen** [fluent-plugins-nursery/fluent-plugin-bigquery#198]
## Environments

- fluentd version: v1.15 
- plugin version: 2.3.0

## Configuration
```
<match hofund.amlrequests>
  @type         bigquery_insert

  auth_method   json_key
  json_key      /fluentd/secrets/bigquery.json
  project       myproject
  dataset       mydataset
  table         mytable
  fetch_schema  true
</match>
```

## Expected Behavior
Should insert into bigquery without errors

## Actual Behavior
Got the error: "wrong number of arguments (given 5, expected 3..4)". The full stack is listed below

## Log (if you have)
```
2022-09-19 13:58:25 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="wrong number of arguments (given 5, expected 3..4)"
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/bigquery_v2/service.rb:1105:in `insert_all_table_data'
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluent-plugin-bigquery-2.3.0/lib/fluent/plugin/bigquery/writer.rb:86:in `insert_rows'
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluent-plugin-bigquery-2.3.0/lib/fluent/plugin/out_bigquery_insert.rb:102:in `insert'
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluent-plugin-bigquery-2.3.0/lib/fluent/plugin/out_bigquery_insert.rb:98:in `write'
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:1180:in `try_flush'
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'
  2022-09-19 13:58:25 +0000 [warn]: #0 /usr/local/lib/ruby/gems/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by joker1007** [comment]
Probably, fixed by https://github.com/fluent-plugins-nursery/fluent-plugin-bigquery/pull/199
