### ISSUE TITLE
Invalid field type: GEOGRAPHY

### ISSUE THREAD

**Issue by kschouw** [fluent-plugins-nursery/fluent-plugin-bigquery#201]
## Environments

- fluentd version: 1.13.3
- plugin version: 3.0.0

## Configuration

```
<match server_**>
  @type         bigquery_load
  <buffer tag>
    path bigquery.*.buffer
    flush_at_shutdown true
    chunk_limit_size 512KB
    flush_interval 15
  </buffer>
  auth_method   json_key
  project        dev-1
  dataset       testing
  table           ${tag}
  json_key     /etc/auth.json
  fetch_schema  true
</match>
```

## Expected Behavior

No errors with row(s) being loaded into BigQuery

## Actual Behavior

An error saying `Invalid field type: GEOGRAPHY`.

## Log (if you have)

Sample JSON payload:

```
{
   "geo":"POINT(18.6294 -33.8943)"
}
```

Fluent debug logs:

```
2022-10-25 15:45:17 +0200 [warn]: #0 emit transaction failed: error_class=Fluent::ConfigError error="Invalid field type: GEOGRAPHY" location="/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:232:in `block in load_schema'" tag="server_event"
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:232:in `block in load_schema'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:224:in `each'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:224:in `load_schema'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/out_bigquery_base.rb:198:in `fetch_schema'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/out_bigquery_base.rb:167:in `format'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/out_bigquery_load.rb:61:in `format'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:998:in `block in handle_stream_simple'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/event.rb:110:in `each'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:997:in `handle_stream_simple'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:883:in `execute_chunking'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:813:in `emit_buffered'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/event_router.rb:97:in `emit_stream'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/event_router.rb:88:in `emit'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/in_forward.rb:355:in `on_message'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/in_forward.rb:226:in `block in handle_connection'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/in_forward.rb:253:in `block (2 levels) in read_messages'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/in_forward.rb:257:in `<<'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/in_forward.rb:257:in `block (2 levels) in read_messages'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin/in_forward.rb:271:in `block in read_messages'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/server.rb:613:in `on_read_without_connection'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:123:in `on_readable'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/io.rb:186:in `on_readable'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2022-10-25 15:45:17 +0200 [warn]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-10-25 15:45:17 +0200 [error]: #0 unexpected error on reading data host="127.0.0.1" port=6956 error_class=Fluent::ConfigError error="Invalid field type: GEOGRAPHY"
  2022-10-25 15:45:17 +0200 [error]: #0 suppressed same stacktrace
```

---

I'm not sure is this an issue with the plugin or fluentd, any assistance would be great!

Thanks.

**Comment by kschouw** [comment]
After manually defining a schema file and setting its path I was able to get this working by using `STRING` for `GEOGRAPHY` field types. 

@joker1007  Would it be possible to add support for `GEOGRAPHY` field type as a `STRING`?

**Comment by joker1007** [comment]
Probably, I can support the `GEOGRAPHY` type.
But, I have never used the `GEOGRAPHY` type.
It will take some time to investigate.

Thanks!!
