### ISSUE TITLE
JSON type support

### ISSUE THREAD

**Issue by pradithya** [fluent-plugins-nursery/fluent-plugin-bigquery#204]
[BigQuery added native JSON support](https://cloud.google.com/bigquery/docs/reference/standard-sql/json-data) early this year.  It allow more flexible access to JSON data and also better cost efficiency compared to storing JSON as string. 
Is there any plan to add the support into the plugin?

**Comment by joker1007** [comment]
Perhaps, if you define a field in the table schema that uses JSON Type and send the JSON data to that field as a string, you can use it in the current plugin version.

**Comment by pradithya** [comment]
It's currently throwing following error
```
2022-12-14 07:22:14 +0000 [warn]: #0 emit transaction failed: error_class=Fluent::ConfigError error="Invalid field type: JSON" location="/fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:232:in `block in load_schema'" tag="quickstart"
  2022-12-14 07:22:14 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:232:in `block in load_schema'
  2022-12-14 07:22:14 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:224:in `each'
  2022-12-14 07:22:14 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/bigquery/schema.rb:224:in `load_schema'
  2022-12-14 07:22:14 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/out_bigquery_base.rb:198:in `fetch_schema'
  2022-12-14 07:22:14 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/out_bigquery_base.rb:167:in `format'
  2022-12-14 07:22:14 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-bigquery-3.0.0/lib/fluent/plugin/out_bigquery_load.rb:61:in `format'
  2022-12-14 07:22:14 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin/output.rb:1039:in `block in handle_stream_simple'
```

I think need to explicitly add it to [FIELD_TYPES](https://github.com/fluent-plugins-nursery/fluent-plugin-bigquery/blob/5c429127627e5cfb1ac374d22dc87dbf2b11b1e3/lib/fluent/plugin/bigquery/schema.rb#L231)

**Comment by joker1007** [comment]
Thanks. I understand what this plugin needs.
I will fix the schema handling.

**Comment by pradithya** [comment]
Thanks @joker1007, we are looking forward to it  ! cc: @leonlnj
